// <auto-generated />
using System.Runtime.CompilerServices;

// ReSharper disable once CheckNamespace
namespace Cake.Kudu.Client
{
    /// <summary>
    /// This namespace contains Kudu clients aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Kudu.Client.Extensions
{
    /// <summary>
    /// This namespace contains IKuduClient extension methods.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Kudu.Client.Command
{
    /// <summary>
    /// This namespace contain Kudu client scommand types.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Kudu.Client.VFS
{
    /// <summary>
    /// This namespace contain Kudu virtual file system types.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}